services:
  app:
    build: ./app
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${APP_METRICS_PORT}:${APP_METRICS_PORT}"
    env_file:
      - .env
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
